baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Diamond Way Buddhism Taiwan'
theme = 'dw'

[[menus.main]]
name = 'Home'
weight = 10
pageRef = '/'

[[menus.main]]
name = 'Meditation'
weight = 20
pageRef = '/meditation'

[[menus.main]]
name = 'Travel'
weight = 30
pageRef = '/travel'
